import { UserRepository } from '@/auth/ports/UserRepository';
import { PasswordHasher } from '@/auth/ports/PasswordHasher';
import { TokenService } from '@/auth/ports/TokenService';
import { VerificationTokenRepository } from '@/auth/ports/VerificationTokenRepository';
import { EmailService } from '@/auth/ports/EmailService';
import { ValidationError } from '@/auth/core/domain/errors';
import { User, UserEntity } from '@/auth/core/domain/User';
import { VerificationToken } from '@/auth/core/domain/VerificationToken';

export interface RegisterUserInput {
  name: string;
  email: string;
  password: string;
  role: 'USER' | 'BANK' | 'PRIVATE' | 'ADMIN';
  phoneNumber?: string;
  country?: string;
  companyName?: string;
  registrationNumber?: string;
}

export interface RegisterUserOutput {
  message: string;
  email: string;
  redirectUrl: string;
}

export class RegisterUserUseCase {
  constructor(
    private userRepository: UserRepository,
    private passwordHasher: PasswordHasher,
    private tokenService: TokenService,
    private verificationTokenRepository: VerificationTokenRepository,
    private emailService: EmailService
  ) {}

  async execute(input: RegisterUserInput): Promise<RegisterUserOutput> {
    // Validate input
    this.validateInput(input);

    // Check if user already exists
    const exists = await this.userRepository.exists(input.email);
    if (exists) {
      throw new ValidationError('User with this email already exists');
    }

    // Hash password
    const hashedPassword = await this.passwordHasher.hash(input.password);

    // Create user entity
    const userEntity: UserEntity = {
      id: '', // Will be generated by database
      name: input.name,
      email: input.email,
      password: hashedPassword,
      role: input.role,
      phoneNumber: input.phoneNumber,
      country: input.country,
      companyName: input.companyName,
      registrationNumber: input.registrationNumber,
      isAuthorized: input.role === 'USER' ? true : false,
      status: 'active',
      emailVerified: null,
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Create user in repository
    const user = await this.userRepository.create(User.create(userEntity));

    // Generate OTP
    const otp = this.tokenService.generateOTP();
    const verificationToken = VerificationToken.create(input.email, otp, 15);

    // Save verification token
    await this.verificationTokenRepository.create(
      input.email,
      otp,
      verificationToken.getExpiresAt()
    );

    // Send verification email
    await this.emailService.sendVerificationEmail(input.email, otp);

    return {
      message: 'Registration successful. Please verify your email.',
      email: input.email,
      redirectUrl: `/auth/verify-otp?email=${encodeURIComponent(input.email)}`
    };
  }

  private validateInput(input: RegisterUserInput): void {
    if (!input.name || !input.email || !input.password || !input.role) {
      throw new ValidationError('Missing required fields');
    }

    if (!this.isValidEmail(input.email)) {
      throw new ValidationError('Invalid email format');
    }

    if (input.password.length < 6) {
      throw new ValidationError('Password must be at least 6 characters');
    }

    if ((input.role === 'BANK' || input.role === 'PRIVATE') && 
        (!input.companyName || !input.registrationNumber)) {
      throw new ValidationError('Provider details (company name and registration number) are required for this role');
    }
  }

  private isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }
}
